Statistics service
SidorovKV/java-explore-with-me pull request #3
Opened 2023-07-18 13:07 UTC by SidorovKV

2023-07-18 17:47 UTC, SidorovKV commented
Логирование добавлено

2023-07-18 21:19 UTC, alexache requested changes

2023-07-18 21:19 UTC, alexache commented on statistics/pom.xml
> +            <version>1.18.28</version>
Версии должны быть указаны только в родительском модуле через dependencyManagement

2023-07-18 21:19 UTC, alexache commented on statistics/stat-client/src/main/java/ru/practicum/statclient/StatClient.java
> +    WebClient webClient = WebClient.builder()
Не помешает модификатор доступа у поля

2023-07-18 21:19 UTC, alexache commented on statistics/stat-client/src/main/java/ru/practicum/statclient/StatClient.java
> +                        .queryParam("uris", uris)
Не получится так напрямую передать список, нужно его конвертировать в строку, где URI перечислены через запятую

2023-07-18 21:19 UTC, alexache commented on statistics/stat-client/src/main/java/ru/practicum/statclient/StatClient.java
> +                .bodyToMono(ViewStatsDto.class)
А как на выходе получается единственное значение, если по интерфейсу вернется список статистики для каждого URI?

2023-07-18 21:19 UTC, alexache commented on statistics/stat-dto/src/main/java/ru/practicum/statdto/EndpointHitDto.java
> +    private String app;
Лучше все же добавить какие-то базовые валидации (я увидел комментарий к ПР)

2023-07-19 11:05 UTC, SidorovKV commented on statistics/stat-client/src/main/java/ru/practicum/statclient/StatClient.java
> +                .bodyToMono(ViewStatsDto.class)
Да) Что-то я проморгал этот момент

2023-07-20 14:34 UTC, merged