Main svc
SidorovKV/java-explore-with-me pull request #4
Opened 2023-07-28 20:12 UTC by SidorovKV

First functional version

2023-07-31 16:41 UTC, alexache requested changes

2023-07-31 16:41 UTC, alexache commented on docker-compose.yml
> +      STATS_SERVER_URL: http://stats-server:9090
Зачем базе знать про сервис статистики?

2023-07-31 16:41 UTC, alexache commented on main-service/pom.xml
> +			<version>${org.mapstruct.version}</version>
Версии нужно задавать только через dependencyManagement в родительском модуле

2023-07-31 16:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/controller/EventController.java
> +        return eventService.getEventByIdPublic(eventId, request.getRemoteAddr());
А разве еще не нужен request.getRemoteURI() в придачу?

2023-07-31 16:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/dto/compilation/NewCompilationDto.java
> +    private final HashSet<Long> events;
Лучше использовать интерфейс Set вместо конкретной реализации HashSet

2023-07-31 16:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/dto/user/UserDto.java
> +    private final String name;
Наверное, здесь тоже не помешают валидации

2023-07-31 16:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/exception/Code409Exception.java
> +public class Code409Exception extends RuntimeException {
Не очень красивое название исключения :) Оно больше говорит о слое представления, чем о непосредственно причине исключения

2023-07-31 16:41 UTC, alexache commented on statistics/stat-client/src/main/java/ru/practicum/statclient/StatClient.java
> +            .baseUrl("http://stats-server:9090")
Почему теперь не из енв параметров?

2023-07-31 17:41 UTC, SidorovKV commented on statistics/stat-client/src/main/java/ru/practicum/statclient/StatClient.java
> +            .baseUrl("http://stats-server:9090")
Уезжал на неделю, уже и забыл о проблеме:
"Not enough variable values available to expand 'stats-server.url'"

Из-за неё же и в компоуз налепил везде урл стат-сервера ещё на прошлой неделе.
Оказалось, фигурные скобки для этих целей в ВёбКлиенте использовать нельзя.
Будем значит доставать так: System.getenv().get("STATS_SERVER_URL"). Или же жёстко прописать?

2023-07-31 17:58 UTC, SidorovKV commented on main-service/src/main/java/ru/practicum/mainservice/controller/EventController.java
> +        return eventService.getEventByIdPublic(eventId, request.getRemoteAddr());
На случай изменения адреса эндпоинта? В принципе, да, логично.

2023-07-31 18:11 UTC, SidorovKV commented on main-service/src/main/java/ru/practicum/mainservice/dto/user/UserDto.java
> +    private final String name;
Это исходящий из бэка ДТО. Его нужно валидировать?

2023-07-31 18:18 UTC, SidorovKV commented on main-service/src/main/java/ru/practicum/mainservice/service/EventService.java
> +        Long confirmedRequests = 0L;
Почему-то только в этом методе вспомнил про "избегайте magic numbers)". А потом об этом благополучно не вспоминал)

2023-07-31 19:04 UTC, SidorovKV commented on main-service/src/main/java/ru/practicum/mainservice/service/CompilationService.java
> +        List<EventConfirmedRequestDto> confirmedRequestDtos =
Тут подсушил

2023-07-31 19:32 UTC, SidorovKV commented on main-service/src/main/java/ru/practicum/mainservice/service/CompilationService.java
> +        List<EventConfirmedRequestDto> confirmedRequestDtos =
Вынес общие методы ИвентСервиса и КомпилайшнСервиса в отдельный вспомогательный класс.

2023-07-31 19:46 UTC, SidorovKV commented on docker-compose.yml
> +      STATS_SERVER_URL: http://stats-server:9090
Не базе, а мейн-сервису. Из него же клиент в статистику запросы шлёт

2023-08-01 12:26 UTC, alexache commented on docker-compose.yml
> +      STATS_SERVER_URL: http://stats-server:9090
Немного не так написал - зачем сервису статистики URI от сервиса статистики? В компоуз выше

2023-08-01 12:27 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/controller/EventController.java
> +        return eventService.getEventByIdPublic(eventId, request.getRemoteAddr());
Просто чтобы не отдавать это на откуп сервиса. Сервису незачем знать, как формируются URI доступа к событию (хотя для получения статистики все равно остается)

2023-08-01 12:29 UTC, SidorovKV commented on docker-compose.yml
> +      STATS_SERVER_URL: http://stats-server:9090
А оттуда я убрал уже

2023-08-01 13:29 UTC, alexache approved these changes

2023-08-01 13:39 UTC, merged